# Generated by Django 4.2.1 on 2023-06-02 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desenvolvedora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite um gênero de jogo', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('lancamento', models.DateField(blank=True, null=True)),
                ('sinopse', models.TextField(help_text='Digite a sinopse do jogo.', max_length=1000)),
                ('desenvolvedora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jogos.desenvolvedora')),
                ('plataforma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jogos.plataforma')),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
    ]
