# Generated by Django 4.2.1 on 2023-06-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0002_jogo_imagem_jogo_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='data_publicacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
