# Generated by Django 4.2.1 on 2023-06-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0004_alter_jogo_data_publicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='trailer_youtube',
            field=models.TextField(default='', help_text='Link do trailer do jogo.', max_length=1000),
        ),
    ]
