# Generated by Django 4.2.1 on 2023-06-04 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0005_jogo_trailer_youtube'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogo',
            name='trailer_youtube',
        ),
    ]
