# Generated by Django 4.2.1 on 2023-06-04 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0008_alter_jogo_plataforma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='plataforma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jogos.plataforma'),
        ),
    ]
